---

- name: nginx
  hosts: frontend
  become: true
  gather_facts: no
  roles:
    - nginx-frontend

- name: apache
  hosts: backend
  become: true
  gather_facts: no
  roles:
    - apache-backend



